version: '3'

services:
  node:
    container_name: node-service
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /project
    volumes:
      - ./:/project
    ports:
      - 8080:3000
